### ISSUE TITLE
[Request] allow user to specify dev keys to avoid quota issues

### ISSUE THREAD

**Issue by mwpher** [np1/pafy#28]
Hi,

I'm trying to write a script that involves grabbing a lot of YouTube data at once. The result of this is that YouTube eventually gives an error 403 due to my client making too many requests. If I was able to specify a YouTube API key that Pafy would send along with its requests, YouTube Woodgeard the client much more leeway.

I'm going to look into trying to add this feature myself (I believe in giving what I can to open-source projects), but since I'm a newbie to Python, you shouldn't count on it. :/

Thanks for the awesome library!
--Matt

**Comment by ids1024** [comment]
With commit ce36d7cadd84b2acf32c578716220c2ed6405c6f, api keys are not only allowed, but required, because gdata v3 requires them. A default is included with pafy, which can be customized by your script by calling `pafy.set_api_key(YOURKEY)`.
