### ISSUE TITLE
ytdl script - ascii not in range [v=HoMzLLWNV1g]

### ISSUE THREAD

**Issue by serl** [np1/pafy#67]
Video's title has an "ä", that's what happens:

    $ ytdl https://www.youtube.com/watch?v=HoMzLLWNV1g -a
    Traceback (most recent call last):
      File "/usr/local/bin/ytdl", line 170, in <module>
        main()
      File "/usr/local/bin/ytdl", line 145, in main
        download(vid, audio=args.a)
      File "/usr/local/bin/ytdl", line 62, in download
        print(dl_str.format(stream.filename, size))
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 20: ordinal not in range(128)

**Comment by ids1024** [comment]
Should be fixed by commit 106883119a9f83ffa7dafc386a17dddbd192955.

Test it by installing the develop branch: `pip install --upgrade https://github.com/np1/pafy/archive/develop.zip`
