### ISSUE TITLE
Legality of using pafy?

### ISSUE THREAD

**Issue by mikeder** [np1/pafy#73]
Hello, it was just brought to my attention that downloading/storing audiovisual content from YouTube is against their TOS. Just curious what you think about that in regards to using something like pafy? I am in no way against using pafy but I don't want to get smacked w/ a lawsuit you know?

II. Prohibitions
...
![tos](https://cloud.githubusercontent.com/assets/10190630/5887382/ad64e200-a39a-11e4-8df3-dccbeb103af5.PNG)

https://developers.google.com/youtube/terms

**Comment by nwaomachux** [comment]
If you download, watch and delete, it amounts to the same thing that your browser does: visit the link, the video streams (downloads to your PC), you watch it, and leave the page. Sounds same to me.

**Comment by mikeder** [comment]
What about say, downloading audio streams, converting them and deleting the original? Can YouTube even tell that pafy is pulling audio only from them?

**Comment by nwaomachux** [comment]
Well, Youtube can only tell from the useragent string if it's not set properly, asides that, it's the end of the whole thing. That's all that I know.

**Comment by np1** [comment]
I'm not a legal expert so my opinion would not serve you well. If this is a genuine concern you have I would suggest you seek legal advice.

**Comment by nwaomachux** [comment]
@np1 I quite agree with you. Personally, I don't even disturb myself with issues like that since I don't sell the contents but to make them portable for me like situations when I don't have access to the internet. And I've used it quite a lot to watch some programming tutorials.

**Comment by mikeder** [comment]
Fair enough, I didn't really expect legal advice. I was just curious on your views about it is all. At the end of the day I'm going to keep using pafy anyway. Thanks for your time and efforts!
