### ISSUE TITLE
pafy gets stuck in loop with country-restricted video

### ISSUE THREAD

**Issue by patrickjahns** [np1/pafy#74]
Hey, 

today while trying to use pafy I stumpled over this

>[2015-02-02 13:22:00,370] [DEBUG] [fetch_decode] encoding unknown
>[2015-02-02 13:22:00,371] [DEBUG] [get_video_info] Fetched video info
>[2015-02-02 13:22:00,371] [DEBUG] [get_video_info] Age verification video

Is there anyway to fail gracefully ?

**Comment by np1** [comment]
What is the issue? It doesn't look to me like it's failing. Those are standard debug log messages.

**Comment by patrickjahns** [comment]
It gets stuck at at a loop displaying only these debug messages over and over again

**Comment by np1** [comment]
I see. That was not clear to me. 
Could you show me some code I could run to try to reproduce the issue?

**Comment by patrickjahns** [comment]
Here is a trace log:

> File "googlemusicsync.py", line 349, in youtube_sync
>    video = pafy.new(youtubewatchurl+''+trackid)
>  File "/home/user/scripts/googlemusicsync/pafy.py", line 137, in new
>    return Pafy(url, basic, gdata, signature, size, callback)
>  File "/home/user/scripts/googlemusicsync/pafy.py", line 1046, in __init__
>    self.fetch_basic()
>  File "/home/user/scripts/googlemusicsync/pafy.py", line 1061, in fetch_basic
>    self._fetch_basic()
>  File "/home/user/scripts/googlemusicsync/pafy.py", line 1095, in _fetch_basic
>    allinfo = get_video_info(self.videoid, newurl=info_url)
>  File "/home/user/scripts/googlemusicsync/pafy.py", line 153, in get_video_info
>    info = get_video_info(video_id, newurl)
>  File "/home/user/scripts/googlemusicsync/pafy.py", line 153, in get_video_info
>    info = get_video_info(video_id, newurl)
>  File "/home/user/scripts/googlemusicsync/pafy.py", line 153, in get_video_info
>    info = get_video_info(video_id, newurl)

The code in my script
>    for track in tracks:
>        trackid = track['snippet']['resourceId']['videoId']
>        video = pafy.new(youtubewatchurl+''+trackid)

I have removed the video that caused the issue from the playlist and can`t recover it so you can trace the error. For now it seems that there is an error ("age verification?") with the video and pafy regresses deeper and deeper without failing

**Comment by np1** [comment]
I managed to reproduce the error with that video (`knkkkjiapa8`), thanks, I will investigate more!

**Comment by np1** [comment]
This bug was introduced in version 0.3.70 and has now been fixed in v0.3.72
