### ISSUE TITLE
Use Youtube Data API v3

### ISSUE THREAD

**Issue by ids1024** [np1/pafy#78]
https://developers.google.com/youtube/2.0/reference
> Note: The YouTube Data API (v2) has been officially deprecated as of March 4, 2014. Please refer to our deprecation policy for more information. Please use the YouTube Data API (v3) for new integrations and migrate applications still using the v2 API to the v3 API as well.

https://developers.google.com/youtube/terms#deprecation
> Google will announce if it intends to discontinue or make backwards incompatible changes to this API or Service. Google will use commercially reasonable efforts to continue to operate those YouTube API versions and features identified at http://developers.google.com/youtube/youtube-api-list without these changes until the later of: (i) one year after the announcement or (ii) April 20, 2015, unless (as Google determines in its reasonable good faith judgment): 

It looks like v2 of the API will only be available until April 20, although it does not seem to explicitly say that it will be disabled by then. Therefore, pafy should probably be using v3 by that date.

**Comment by lol768** [comment]
https://support.google.com/youtube/answer/6098135?p=yt_devicesupport&hl=en&rd=1

>As we upgrade the YouTube Data API to bring more features, we’ll begin shutting down the old version on April 20, 2015. This will result in the current YouTube app not working on certain device models from 2012 and older.

**Comment by ids1024** [comment]
> Might be time to start doing scraping of search pages. API v3 doesn't support anonymous access :/

It does allow the user to be anonymous (i.e. not logged in), but mpsyt would need an API key. That could be problematic if it is violating the TOS by downloading videos and playing videos in something other than the official YouTube player.

The device support video could be excluded from results as a very temporary solution (though not really necessary), but that is obviously not a long term solution.

**Comment by lol768** [comment]
*@ids1024 said:*
> That could be problematic if it is violating the TOS by downloading videos and playing videos in something other than the official YouTube player.

In addition to the whole ToS issue, it's also worth keeping in mind that the API key is given a quota. There's little stopping a single malicious user from using up the entire application's quota (other than [this](https://developers.google.com/console/help/#cappingusage)):

*[Google](https://developers.google.com/youtube/2.0/deprecation_faq) said:*
> The most significant difference between the v2 and v3 systems is that v3 provides a global quota pool, which v2 did not do. In v2, requests made with a single developer key but coming from distinct IP addresses or from distinct authenticated users couldn’t cause global quota errors for that developer key—the worst that would happen would be a localized quota error associated with the IP address or YouTube channel.

> In v3, there is a global quota pool (of 50 million units/day), and all API calls that are associated with a specific project in the Developers Console decrement quota from that pool. Therefore, it is theoretically possible for a single IP address or channel to consume all of the quota associated with an API registration, which could lead to an outage that affects other users.

According to the YouTube blog, it could be as early as **two to three weeks** before applications like [np1/mps-youtube](https://github.com/np1/mps-youtube) are no longer able to use v2 of the API. As you said, filtering out the warning video would definitely be a short-term solution.

*[YouTube](http://youtube-eng.blogspot.co.uk/2015/04/bye-bye-youtube-data-api-v2.html) said:*
> In early May, Data API v2 video calls will start returning only the warning video introduced on April 20. Users will not be able to view other videos on apps that use the v2 API video calls. See youtube.com/devicesupport for affected devices.

> By late May, v2 API calls except for comments and captions will receive 410 Gone HTTP responses. You can test your application’s reaction to this response by pointing the application at eol.gdata.youtube.com instead of gdata.youtube.com. While you should migrate your app as soon as possible, these features will work in the Data API v2 until the end of July 2015 to avoid any outages.

**Comment by guaraqe** [comment]
I'm following it more or less, would that mean that in order to use the API we would have to provide a Google username/password? Or at least is that a possibility with API V3? In any way, it's a bummer...

**Comment by lol768** [comment]
@guaraqe 

My understanding is that each user would need to sign-up in the developer console and grab an API key to use with the application to completely avoid the issues with rate limiting.

**Comment by ids1024** [comment]
@lol768 I don't think the 50 million units/day limit is much of an issue. All the users of pafy will not use nearly that much, and I don't think it is very likely that the api key would be taken and used maliciously and reach the limit that way. I have gotten an api key to try the gdata 3 api. It gives the options of a "server key", a "browser key", an "android key", or an "ios key". Browser key seems the most appropriate. That suggests it is meant to be used by client side javascript code, so any use of it would have the same issues as mpsyt since anyone could extract the key from the javascript.

The TOS issue still is relevant, and it may be better to just scrape results from the html, although that is sub-optimal. Either way, something has to been done, and there is not all to much time before it stops working.

**Comment by ids1024** [comment]
I have been looking at the documentation, and gdata 3 also allows a user quota to be set to prevent a single user from using up the quota: https://developers.google.com/console/help/#cappingusage

The quota should not be an issue, but the other issue remains.

**Comment by lol768** [comment]
@ids1024 
>I have been looking at the documentation, and gdata 3 also allows a user quota to be set to prevent a single user from using up the quota: https://developers.google.com/console/help/#cappingusage

The documentation seems to suggest it's up to the application to send the IP address or a unique user identifier *if it's server-side*, so I'm assuming something like this project wouldn't need to send either the `quotaUser` or `userIp` parameters? If so, are the quotas applied by default by IP address? The page states this which makes me think otherwise:

> If you don't send the userIp or quotaUser parameters, then all calls are listed as coming directly from the server-side machine itself, in which case calls can't be capped by user.

If the python *does* send the quotaUser or userIp parameter with the request, what stops a malicious user from just editing the code and making it unique for each request (or just stripping it from all requests) and then exceeding the application's quota usage again? Since the code is executed on the client, I'm not sure much can be done to prevent this.

What if each user was instructed to create their own API key upon installing the application?

**Comment by guaraqe** [comment]
Well, creating API keys automatically does not seem really practical, and both option require logging in. So if that should be made by users, that is an equivalent to a harder login.

https://developers.google.com/identity/protocols/OAuth2
https://developers.google.com/console/help/#generatingdevkeys

**Comment by lol768** [comment]
> So if that should be made by users, that is an equivalent to a harder login.

Yeah, it'd be inconvenient for users which is one of the reasons I'm in favour of just scraping the search results page.

**Comment by lol768** [comment]
Looks like v2 is completely dead now. Only getting one result which is https://youtube.com/devicesupport

**Comment by andresmrm** [comment]
Just installed mps-youtube, got that "error" and came all way here looking for advice. I really picked the right time for this! =P

**Comment by lol768** [comment]
Had a play with beautiful soup and YouTube's channel page to try and see if I could use it for the 'user' command. I tried using the channel list view: https://www.youtube.com/user/%s/videos?flow=list&view=0&sort=dd&live_view=500&spf=navigate

![](http://i.imgur.com/FAz70vN.png)

It sorta works. (messy) code:

```python
def do_user_search(param):
    url = "https://www.youtube.com/user/%s/videos?flow=list&view=0&sort=dd&live_view=500&spf=navigate" % param
    content = requests.get(url)
    response = content.json()
    soup = bs4.BeautifulSoup(response['body']['content'])
    for video in soup.select(".feed-item-container"):
        title = video.select(".yt-uix-tile-link")[0]['title']
        identifier = video.select(".yt-uix-tile-link")[0]['href'][9:]
        duration = parse_duration(video.select(".video-time")[0].text)
        views = video.select(".yt-lockup-meta-info li:last-child")[0].text
        print("Got a video", title, duration, views)

def parse_duration(duration):
    # hours:seconds:minutes (I checked, no days are ever displayed)
    parts = duration.split(":")
    if len(parts) == 3:
        # hours                        mins                 secs
        secs = 3600 * int(parts[0]) + 60 * int(parts[1]) + int(parts[2])
    else:
        # mins                 secs
        secs = 60 * int(parts[0]) + int(parts[1])

    return secs
```

**Problems with my approach:**

* Pagination is not going to be fun. Scraping the mobile site might be easier, but the desktop site uses a bunch of JS to load new items as a continuation of a previous action.
* Obviously the minute YouTube changes the page, the scraping breaks. That said, we can be reasonably certain the functionality we need will always be there (without the need of an API key which can be abused). Unlike the API, it's probably unlikely functionality will be removed and not replaced.
* Seems a bit slower than API v2.

**Advantages:**

* Doesn't require an API key. No per-key quotas.
* Harder to block. Can spoof Firefox/Chrome's user agent if necessary.

**Comment by ids1024** [comment]
@np1 What do you think about html scraping vs gdata v3?

**Comment by ids1024** [comment]
Pafy is using gdata v3 as of commit ce36d7cadd84b2acf32c578716220c2ed6405c6f.
