### ISSUE TITLE
error: python-pafy: signature from "Johannes Löthberg <johannes@kyriasis.com>" is unknown trust

### ISSUE THREAD

**Issue by marek287** [np1/pafy#99]
I m getting this error while trying to install pythom-pafy (Arch linux). 
error: python-pafy: signature from "Johannes Löthberg <johannes@kyriasis.com>" is unknown trust
:: File /var/cache/pacman/pkg/python-pafy-0.3.74-1-any.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).

**Comment by ids1024** [comment]
This is an Archlinux issue, not a pafy issue. Try asking on the archlinux irc channel, forums, mailing list, etc.

**Comment by marek287** [comment]
Finally I found solution.
https://bbs.archlinux.org/viewtopic.php?id=190380
I made empty dirmngr_ldapservers.conf file to /root/.gnupg/ folder solved this problem.
